/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module flip.serialize;
export import flip;


import flag;

import simdjson;
import std;

export namespace simdjson{

void tag_invoke(serialize_tag, builder::string_builder& builder,const Flip& payload){
    switch (payload) {
    case Flip::None:
        builder.append("None");
        break;
    case Flip::Horizontal:
        builder.append("Horizontal");
        break;
    case Flip::Vertical:
        builder.append("Vertical");
        break;
    }
}

auto tag_invoke(deserialize_tag, ondemand::document& val,Flip& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "None") {
        payload = Flip::None;
        return simdjson::SUCCESS;
    }
    if (value == "Horizontal") {
        payload = Flip::Horizontal;
        return simdjson::SUCCESS;
    }
    if (value == "Vertical") {
        payload = Flip::Vertical;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,Flip& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "None") {
        payload = Flip::None;
        return simdjson::SUCCESS;
    }
    if (value == "Horizontal") {
        payload = Flip::Horizontal;
        return simdjson::SUCCESS;
    }
    if (value == "Vertical") {
        payload = Flip::Vertical;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Flags<Flip>& payload){
    builder.start_array();
    if(payload.Value()==0){
        builder.append("None");
    }
    if (payload & Flip::Horizontal){
        builder.append_comma();
        builder.append("Horizontal");
    }
    if (payload & Flip::Vertical){
        builder.append_comma();
        builder.append("Vertical");
    }
    builder.end_array();
}

auto tag_invoke(deserialize_tag, ondemand::document& val,Flags<Flip>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "None") {
            payload |= Flip::None;
            match = true;
        }
        if (value == "Horizontal") {
            payload |= Flip::Horizontal;
            match = true;
        }
        if (value == "Vertical") {
            payload |= Flip::Vertical;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,Flags<Flip>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "None") {
            payload |= Flip::None;
            match = true;
        }
        if (value == "Horizontal") {
            payload |= Flip::Horizontal;
            match = true;
        }
        if (value == "Vertical") {
            payload |= Flip::Vertical;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

}
