/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module inputconfig.serialize;
export import inputconfig;

import key.serialize;
import padkey.serialize;
import mousekey.serialize;


import simdjson;
import std;

export namespace simdjson{

void tag_invoke(serialize_tag, builder::string_builder& builder,const KeyboardInput& payload){
    builder.start_object();
    builder.template append_key_value<"m_key">(payload.m_key);
    builder.append_comma();
    builder.template append_key_value<"m_scale">(payload.m_scale);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,KeyboardInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_key"].get(payload.m_key))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,KeyboardInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_key"].get(payload.m_key))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const GamepadButtonInput& payload){
    builder.start_object();
    builder.template append_key_value<"m_button">(payload.m_button);
    builder.append_comma();
    builder.template append_key_value<"m_scale">(payload.m_scale);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,GamepadButtonInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_button"].get(payload.m_button))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,GamepadButtonInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_button"].get(payload.m_button))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const GamepadAxisInput& payload){
    builder.start_object();
    builder.template append_key_value<"m_axis">(payload.m_axis);
    builder.append_comma();
    builder.template append_key_value<"m_scale">(payload.m_scale);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,GamepadAxisInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_axis"].get(payload.m_axis))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,GamepadAxisInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_axis"].get(payload.m_axis))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const MouseButtonInput& payload){
    builder.start_object();
    builder.template append_key_value<"m_type">(payload.m_type);
    builder.append_comma();
    builder.template append_key_value<"m_scale">(payload.m_scale);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,MouseButtonInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_type"].get(payload.m_type))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,MouseButtonInput& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_type"].get(payload.m_type))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const InputActionConfig& payload){
    builder.start_object();
    builder.template append_key_value<"m_name">(payload.m_name);
    builder.append_comma();
    builder.template append_key_value<"m_keyboard">(payload.m_keyboard);
    builder.append_comma();
    builder.template append_key_value<"m_gamepad">(payload.m_gamepad);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,InputActionConfig& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_name"].get(payload.m_name))){
        return error;
    }
    if((error=obj["m_keyboard"].get(payload.m_keyboard))){
        return error;
    }
    if((error=obj["m_gamepad"].get(payload.m_gamepad))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,InputActionConfig& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_name"].get(payload.m_name))){
        return error;
    }
    if((error=obj["m_keyboard"].get(payload.m_keyboard))){
        return error;
    }
    if((error=obj["m_gamepad"].get(payload.m_gamepad))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const InputAxisConfig& payload){
    builder.start_object();
    builder.template append_key_value<"m_name">(payload.m_name);
    builder.append_comma();
    builder.template append_key_value<"m_keyboard">(payload.m_keyboard);
    builder.append_comma();
    builder.template append_key_value<"m_gamepad_axis">(payload.m_gamepad_axis);
    builder.append_comma();
    builder.template append_key_value<"m_gamepad_button">(payload.m_gamepad_button);
    builder.append_comma();
    builder.template append_key_value<"m_mouse_vertical">(payload.m_mouse_vertical);
    builder.append_comma();
    builder.template append_key_value<"m_mouse_horizontal">(payload.m_mouse_horizontal);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,InputAxisConfig& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_name"].get(payload.m_name))){
        return error;
    }
    if((error=obj["m_keyboard"].get(payload.m_keyboard))){
        return error;
    }
    if((error=obj["m_gamepad_axis"].get(payload.m_gamepad_axis))){
        return error;
    }
    if((error=obj["m_gamepad_button"].get(payload.m_gamepad_button))){
        return error;
    }
    if((error=obj["m_mouse_vertical"].get(payload.m_mouse_vertical))){
        return error;
    }
    if((error=obj["m_mouse_horizontal"].get(payload.m_mouse_horizontal))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,InputAxisConfig& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_name"].get(payload.m_name))){
        return error;
    }
    if((error=obj["m_keyboard"].get(payload.m_keyboard))){
        return error;
    }
    if((error=obj["m_gamepad_axis"].get(payload.m_gamepad_axis))){
        return error;
    }
    if((error=obj["m_gamepad_button"].get(payload.m_gamepad_button))){
        return error;
    }
    if((error=obj["m_mouse_vertical"].get(payload.m_mouse_vertical))){
        return error;
    }
    if((error=obj["m_mouse_horizontal"].get(payload.m_mouse_horizontal))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const InputConfig& payload){
    builder.start_object();
    builder.template append_key_value<"m_action">(payload.m_action);
    builder.append_comma();
    builder.template append_key_value<"m_axis">(payload.m_axis);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,InputConfig& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_action"].get(payload.m_action))){
        return error;
    }
    if((error=obj["m_axis"].get(payload.m_axis))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,InputConfig& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_action"].get(payload.m_action))){
        return error;
    }
    if((error=obj["m_axis"].get(payload.m_axis))){
        return error;
    }
    return simdjson::SUCCESS;
}

}
