/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module math.serialize;
export import math;




import simdjson;
import std;

export namespace simdjson{

void tag_invoke(serialize_tag, builder::string_builder& builder,const Vec2& payload){
    builder.start_object();
    builder.template append_key_value<"x">(payload.x);
    builder.append_comma();
    builder.template append_key_value<"y">(payload.y);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Vec2& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["x"].get(payload.x))){
        return error;
    }
    if((error=obj["y"].get(payload.y))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Vec2& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["x"].get(payload.x))){
        return error;
    }
    if((error=obj["y"].get(payload.y))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Color& payload){
    builder.start_object();
    builder.template append_key_value<"r">(payload.r);
    builder.append_comma();
    builder.template append_key_value<"g">(payload.g);
    builder.append_comma();
    builder.template append_key_value<"b">(payload.b);
    builder.append_comma();
    builder.template append_key_value<"a">(payload.a);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Color& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["r"].get(payload.r))){
        return error;
    }
    if((error=obj["g"].get(payload.g))){
        return error;
    }
    if((error=obj["b"].get(payload.b))){
        return error;
    }
    if((error=obj["a"].get(payload.a))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Color& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["r"].get(payload.r))){
        return error;
    }
    if((error=obj["g"].get(payload.g))){
        return error;
    }
    if((error=obj["b"].get(payload.b))){
        return error;
    }
    if((error=obj["a"].get(payload.a))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Rect& payload){
    builder.start_object();
    builder.template append_key_value<"m_center">(payload.m_center);
    builder.append_comma();
    builder.template append_key_value<"m_half_size">(payload.m_half_size);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Rect& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_center"].get(payload.m_center))){
        return error;
    }
    if((error=obj["m_half_size"].get(payload.m_half_size))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Rect& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_center"].get(payload.m_center))){
        return error;
    }
    if((error=obj["m_half_size"].get(payload.m_half_size))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Circle& payload){
    builder.start_object();
    builder.template append_key_value<"m_radius">(payload.m_radius);
    builder.append_comma();
    builder.template append_key_value<"m_position">(payload.m_position);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Circle& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_radius"].get(payload.m_radius))){
        return error;
    }
    if((error=obj["m_position"].get(payload.m_position))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Circle& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_radius"].get(payload.m_radius))){
        return error;
    }
    if((error=obj["m_position"].get(payload.m_position))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Region& payload){
    builder.start_object();
    builder.template append_key_value<"m_topleft">(payload.m_topleft);
    builder.append_comma();
    builder.template append_key_value<"m_size">(payload.m_size);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Region& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_topleft"].get(payload.m_topleft))){
        return error;
    }
    if((error=obj["m_size"].get(payload.m_size))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Region& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_topleft"].get(payload.m_topleft))){
        return error;
    }
    if((error=obj["m_size"].get(payload.m_size))){
        return error;
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Transform& payload){
    builder.start_object();
    builder.template append_key_value<"m_position">(payload.m_position);
    builder.append_comma();
    builder.template append_key_value<"m_rotation">(payload.m_rotation);
    builder.append_comma();
    builder.template append_key_value<"m_scale">(payload.m_scale);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Transform& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_position"].get(payload.m_position))){
        return error;
    }
    if((error=obj["m_rotation"].get(payload.m_rotation))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Transform& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_position"].get(payload.m_position))){
        return error;
    }
    if((error=obj["m_rotation"].get(payload.m_rotation))){
        return error;
    }
    if((error=obj["m_scale"].get(payload.m_scale))){
        return error;
    }
    return simdjson::SUCCESS;
}

}
