/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module mousekey.serialize;
export import mousekey;


import flag;

import simdjson;
import std;

export namespace simdjson{

void tag_invoke(serialize_tag, builder::string_builder& builder,const MouseButtonType& payload){
    switch (payload) {
    case MouseButtonType::Left:
        builder.append("Left");
        break;
    case MouseButtonType::Right:
        builder.append("Right");
        break;
    case MouseButtonType::Middle:
        builder.append("Middle");
        break;
    case MouseButtonType::X1:
        builder.append("X1");
        break;
    case MouseButtonType::X2:
        builder.append("X2");
        break;
    }
}

auto tag_invoke(deserialize_tag, ondemand::document& val,MouseButtonType& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "Left") {
        payload = MouseButtonType::Left;
        return simdjson::SUCCESS;
    }
    if (value == "Right") {
        payload = MouseButtonType::Right;
        return simdjson::SUCCESS;
    }
    if (value == "Middle") {
        payload = MouseButtonType::Middle;
        return simdjson::SUCCESS;
    }
    if (value == "X1") {
        payload = MouseButtonType::X1;
        return simdjson::SUCCESS;
    }
    if (value == "X2") {
        payload = MouseButtonType::X2;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,MouseButtonType& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "Left") {
        payload = MouseButtonType::Left;
        return simdjson::SUCCESS;
    }
    if (value == "Right") {
        payload = MouseButtonType::Right;
        return simdjson::SUCCESS;
    }
    if (value == "Middle") {
        payload = MouseButtonType::Middle;
        return simdjson::SUCCESS;
    }
    if (value == "X1") {
        payload = MouseButtonType::X1;
        return simdjson::SUCCESS;
    }
    if (value == "X2") {
        payload = MouseButtonType::X2;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Flags<MouseButtonType>& payload){
    builder.start_array();

    if (payload & MouseButtonType::Left){
        
        builder.append("Left");
    }
    if (payload & MouseButtonType::Right){
        builder.append_comma();
        builder.append("Right");
    }
    if (payload & MouseButtonType::Middle){
        builder.append_comma();
        builder.append("Middle");
    }
    if (payload & MouseButtonType::X1){
        builder.append_comma();
        builder.append("X1");
    }
    if (payload & MouseButtonType::X2){
        builder.append_comma();
        builder.append("X2");
    }
    builder.end_array();
}

auto tag_invoke(deserialize_tag, ondemand::document& val,Flags<MouseButtonType>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "Left") {
            payload |= MouseButtonType::Left;
            match = true;
        }
        if (value == "Right") {
            payload |= MouseButtonType::Right;
            match = true;
        }
        if (value == "Middle") {
            payload |= MouseButtonType::Middle;
            match = true;
        }
        if (value == "X1") {
            payload |= MouseButtonType::X1;
            match = true;
        }
        if (value == "X2") {
            payload |= MouseButtonType::X2;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,Flags<MouseButtonType>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "Left") {
            payload |= MouseButtonType::Left;
            match = true;
        }
        if (value == "Right") {
            payload |= MouseButtonType::Right;
            match = true;
        }
        if (value == "Middle") {
            payload |= MouseButtonType::Middle;
            match = true;
        }
        if (value == "X1") {
            payload |= MouseButtonType::X1;
            match = true;
        }
        if (value == "X2") {
            payload |= MouseButtonType::X2;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

}
