/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module padkey.serialize;
export import padkey;


import flag;

import simdjson;
import std;

export namespace simdjson{

void tag_invoke(serialize_tag, builder::string_builder& builder,const GamepadAxisType& payload){
    switch (payload) {
    case GamepadAxisType::Invalid:
        builder.append("Invalid");
        break;
    case GamepadAxisType::LeftX:
        builder.append("LeftX");
        break;
    case GamepadAxisType::LeftY:
        builder.append("LeftY");
        break;
    case GamepadAxisType::RightX:
        builder.append("RightX");
        break;
    case GamepadAxisType::RightY:
        builder.append("RightY");
        break;
    case GamepadAxisType::LeftTrigger:
        builder.append("LeftTrigger");
        break;
    case GamepadAxisType::RightTrigger:
        builder.append("RightTrigger");
        break;
    }
}

auto tag_invoke(deserialize_tag, ondemand::document& val,GamepadAxisType& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "Invalid") {
        payload = GamepadAxisType::Invalid;
        return simdjson::SUCCESS;
    }
    if (value == "LeftX") {
        payload = GamepadAxisType::LeftX;
        return simdjson::SUCCESS;
    }
    if (value == "LeftY") {
        payload = GamepadAxisType::LeftY;
        return simdjson::SUCCESS;
    }
    if (value == "RightX") {
        payload = GamepadAxisType::RightX;
        return simdjson::SUCCESS;
    }
    if (value == "RightY") {
        payload = GamepadAxisType::RightY;
        return simdjson::SUCCESS;
    }
    if (value == "LeftTrigger") {
        payload = GamepadAxisType::LeftTrigger;
        return simdjson::SUCCESS;
    }
    if (value == "RightTrigger") {
        payload = GamepadAxisType::RightTrigger;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,GamepadAxisType& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "Invalid") {
        payload = GamepadAxisType::Invalid;
        return simdjson::SUCCESS;
    }
    if (value == "LeftX") {
        payload = GamepadAxisType::LeftX;
        return simdjson::SUCCESS;
    }
    if (value == "LeftY") {
        payload = GamepadAxisType::LeftY;
        return simdjson::SUCCESS;
    }
    if (value == "RightX") {
        payload = GamepadAxisType::RightX;
        return simdjson::SUCCESS;
    }
    if (value == "RightY") {
        payload = GamepadAxisType::RightY;
        return simdjson::SUCCESS;
    }
    if (value == "LeftTrigger") {
        payload = GamepadAxisType::LeftTrigger;
        return simdjson::SUCCESS;
    }
    if (value == "RightTrigger") {
        payload = GamepadAxisType::RightTrigger;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Flags<GamepadAxisType>& payload){
    builder.start_array();
    if(payload.Value()==0){
        builder.append("LeftX");
    }
    if (payload & GamepadAxisType::Invalid){
        
        builder.append("Invalid");
    }
    if (payload & GamepadAxisType::LeftY){
        builder.append_comma();
        builder.append("LeftY");
    }
    if (payload & GamepadAxisType::RightX){
        builder.append_comma();
        builder.append("RightX");
    }
    if (payload & GamepadAxisType::RightY){
        builder.append_comma();
        builder.append("RightY");
    }
    if (payload & GamepadAxisType::LeftTrigger){
        builder.append_comma();
        builder.append("LeftTrigger");
    }
    if (payload & GamepadAxisType::RightTrigger){
        builder.append_comma();
        builder.append("RightTrigger");
    }
    builder.end_array();
}

auto tag_invoke(deserialize_tag, ondemand::document& val,Flags<GamepadAxisType>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "Invalid") {
            payload |= GamepadAxisType::Invalid;
            match = true;
        }
        if (value == "LeftX") {
            payload |= GamepadAxisType::LeftX;
            match = true;
        }
        if (value == "LeftY") {
            payload |= GamepadAxisType::LeftY;
            match = true;
        }
        if (value == "RightX") {
            payload |= GamepadAxisType::RightX;
            match = true;
        }
        if (value == "RightY") {
            payload |= GamepadAxisType::RightY;
            match = true;
        }
        if (value == "LeftTrigger") {
            payload |= GamepadAxisType::LeftTrigger;
            match = true;
        }
        if (value == "RightTrigger") {
            payload |= GamepadAxisType::RightTrigger;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,Flags<GamepadAxisType>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "Invalid") {
            payload |= GamepadAxisType::Invalid;
            match = true;
        }
        if (value == "LeftX") {
            payload |= GamepadAxisType::LeftX;
            match = true;
        }
        if (value == "LeftY") {
            payload |= GamepadAxisType::LeftY;
            match = true;
        }
        if (value == "RightX") {
            payload |= GamepadAxisType::RightX;
            match = true;
        }
        if (value == "RightY") {
            payload |= GamepadAxisType::RightY;
            match = true;
        }
        if (value == "LeftTrigger") {
            payload |= GamepadAxisType::LeftTrigger;
            match = true;
        }
        if (value == "RightTrigger") {
            payload |= GamepadAxisType::RightTrigger;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const GamepadButtonType& payload){
    switch (payload) {
    case GamepadButtonType::Invalid:
        builder.append("Invalid");
        break;
    case GamepadButtonType::South:
        builder.append("South");
        break;
    case GamepadButtonType::East:
        builder.append("East");
        break;
    case GamepadButtonType::West:
        builder.append("West");
        break;
    case GamepadButtonType::North:
        builder.append("North");
        break;
    case GamepadButtonType::Back:
        builder.append("Back");
        break;
    case GamepadButtonType::Guide:
        builder.append("Guide");
        break;
    case GamepadButtonType::Start:
        builder.append("Start");
        break;
    case GamepadButtonType::LeftStick:
        builder.append("LeftStick");
        break;
    case GamepadButtonType::RightStick:
        builder.append("RightStick");
        break;
    case GamepadButtonType::LeftShoulder:
        builder.append("LeftShoulder");
        break;
    case GamepadButtonType::RightShoulder:
        builder.append("RightShoulder");
        break;
    case GamepadButtonType::DpadUp:
        builder.append("DpadUp");
        break;
    case GamepadButtonType::DpadDown:
        builder.append("DpadDown");
        break;
    case GamepadButtonType::DpadLeft:
        builder.append("DpadLeft");
        break;
    case GamepadButtonType::DpadRight:
        builder.append("DpadRight");
        break;
    case GamepadButtonType::Misc1:
        builder.append("Misc1");
        break;
    case GamepadButtonType::RightPaddle1:
        builder.append("RightPaddle1");
        break;
    case GamepadButtonType::LeftPaddle1:
        builder.append("LeftPaddle1");
        break;
    case GamepadButtonType::RightPaddle2:
        builder.append("RightPaddle2");
        break;
    case GamepadButtonType::LeftPaddle2:
        builder.append("LeftPaddle2");
        break;
    case GamepadButtonType::Touchpad:
        builder.append("Touchpad");
        break;
    case GamepadButtonType::Misc2:
        builder.append("Misc2");
        break;
    case GamepadButtonType::Misc3:
        builder.append("Misc3");
        break;
    case GamepadButtonType::Misc4:
        builder.append("Misc4");
        break;
    case GamepadButtonType::Misc5:
        builder.append("Misc5");
        break;
    case GamepadButtonType::Misc6:
        builder.append("Misc6");
        break;
    }
}

auto tag_invoke(deserialize_tag, ondemand::document& val,GamepadButtonType& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "Invalid") {
        payload = GamepadButtonType::Invalid;
        return simdjson::SUCCESS;
    }
    if (value == "South") {
        payload = GamepadButtonType::South;
        return simdjson::SUCCESS;
    }
    if (value == "East") {
        payload = GamepadButtonType::East;
        return simdjson::SUCCESS;
    }
    if (value == "West") {
        payload = GamepadButtonType::West;
        return simdjson::SUCCESS;
    }
    if (value == "North") {
        payload = GamepadButtonType::North;
        return simdjson::SUCCESS;
    }
    if (value == "Back") {
        payload = GamepadButtonType::Back;
        return simdjson::SUCCESS;
    }
    if (value == "Guide") {
        payload = GamepadButtonType::Guide;
        return simdjson::SUCCESS;
    }
    if (value == "Start") {
        payload = GamepadButtonType::Start;
        return simdjson::SUCCESS;
    }
    if (value == "LeftStick") {
        payload = GamepadButtonType::LeftStick;
        return simdjson::SUCCESS;
    }
    if (value == "RightStick") {
        payload = GamepadButtonType::RightStick;
        return simdjson::SUCCESS;
    }
    if (value == "LeftShoulder") {
        payload = GamepadButtonType::LeftShoulder;
        return simdjson::SUCCESS;
    }
    if (value == "RightShoulder") {
        payload = GamepadButtonType::RightShoulder;
        return simdjson::SUCCESS;
    }
    if (value == "DpadUp") {
        payload = GamepadButtonType::DpadUp;
        return simdjson::SUCCESS;
    }
    if (value == "DpadDown") {
        payload = GamepadButtonType::DpadDown;
        return simdjson::SUCCESS;
    }
    if (value == "DpadLeft") {
        payload = GamepadButtonType::DpadLeft;
        return simdjson::SUCCESS;
    }
    if (value == "DpadRight") {
        payload = GamepadButtonType::DpadRight;
        return simdjson::SUCCESS;
    }
    if (value == "Misc1") {
        payload = GamepadButtonType::Misc1;
        return simdjson::SUCCESS;
    }
    if (value == "RightPaddle1") {
        payload = GamepadButtonType::RightPaddle1;
        return simdjson::SUCCESS;
    }
    if (value == "LeftPaddle1") {
        payload = GamepadButtonType::LeftPaddle1;
        return simdjson::SUCCESS;
    }
    if (value == "RightPaddle2") {
        payload = GamepadButtonType::RightPaddle2;
        return simdjson::SUCCESS;
    }
    if (value == "LeftPaddle2") {
        payload = GamepadButtonType::LeftPaddle2;
        return simdjson::SUCCESS;
    }
    if (value == "Touchpad") {
        payload = GamepadButtonType::Touchpad;
        return simdjson::SUCCESS;
    }
    if (value == "Misc2") {
        payload = GamepadButtonType::Misc2;
        return simdjson::SUCCESS;
    }
    if (value == "Misc3") {
        payload = GamepadButtonType::Misc3;
        return simdjson::SUCCESS;
    }
    if (value == "Misc4") {
        payload = GamepadButtonType::Misc4;
        return simdjson::SUCCESS;
    }
    if (value == "Misc5") {
        payload = GamepadButtonType::Misc5;
        return simdjson::SUCCESS;
    }
    if (value == "Misc6") {
        payload = GamepadButtonType::Misc6;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,GamepadButtonType& payload){
    std::string_view value;

    auto error = val.get_string().get(value);
    if (error) {
        return error;
    }

    if (value == "Invalid") {
        payload = GamepadButtonType::Invalid;
        return simdjson::SUCCESS;
    }
    if (value == "South") {
        payload = GamepadButtonType::South;
        return simdjson::SUCCESS;
    }
    if (value == "East") {
        payload = GamepadButtonType::East;
        return simdjson::SUCCESS;
    }
    if (value == "West") {
        payload = GamepadButtonType::West;
        return simdjson::SUCCESS;
    }
    if (value == "North") {
        payload = GamepadButtonType::North;
        return simdjson::SUCCESS;
    }
    if (value == "Back") {
        payload = GamepadButtonType::Back;
        return simdjson::SUCCESS;
    }
    if (value == "Guide") {
        payload = GamepadButtonType::Guide;
        return simdjson::SUCCESS;
    }
    if (value == "Start") {
        payload = GamepadButtonType::Start;
        return simdjson::SUCCESS;
    }
    if (value == "LeftStick") {
        payload = GamepadButtonType::LeftStick;
        return simdjson::SUCCESS;
    }
    if (value == "RightStick") {
        payload = GamepadButtonType::RightStick;
        return simdjson::SUCCESS;
    }
    if (value == "LeftShoulder") {
        payload = GamepadButtonType::LeftShoulder;
        return simdjson::SUCCESS;
    }
    if (value == "RightShoulder") {
        payload = GamepadButtonType::RightShoulder;
        return simdjson::SUCCESS;
    }
    if (value == "DpadUp") {
        payload = GamepadButtonType::DpadUp;
        return simdjson::SUCCESS;
    }
    if (value == "DpadDown") {
        payload = GamepadButtonType::DpadDown;
        return simdjson::SUCCESS;
    }
    if (value == "DpadLeft") {
        payload = GamepadButtonType::DpadLeft;
        return simdjson::SUCCESS;
    }
    if (value == "DpadRight") {
        payload = GamepadButtonType::DpadRight;
        return simdjson::SUCCESS;
    }
    if (value == "Misc1") {
        payload = GamepadButtonType::Misc1;
        return simdjson::SUCCESS;
    }
    if (value == "RightPaddle1") {
        payload = GamepadButtonType::RightPaddle1;
        return simdjson::SUCCESS;
    }
    if (value == "LeftPaddle1") {
        payload = GamepadButtonType::LeftPaddle1;
        return simdjson::SUCCESS;
    }
    if (value == "RightPaddle2") {
        payload = GamepadButtonType::RightPaddle2;
        return simdjson::SUCCESS;
    }
    if (value == "LeftPaddle2") {
        payload = GamepadButtonType::LeftPaddle2;
        return simdjson::SUCCESS;
    }
    if (value == "Touchpad") {
        payload = GamepadButtonType::Touchpad;
        return simdjson::SUCCESS;
    }
    if (value == "Misc2") {
        payload = GamepadButtonType::Misc2;
        return simdjson::SUCCESS;
    }
    if (value == "Misc3") {
        payload = GamepadButtonType::Misc3;
        return simdjson::SUCCESS;
    }
    if (value == "Misc4") {
        payload = GamepadButtonType::Misc4;
        return simdjson::SUCCESS;
    }
    if (value == "Misc5") {
        payload = GamepadButtonType::Misc5;
        return simdjson::SUCCESS;
    }
    if (value == "Misc6") {
        payload = GamepadButtonType::Misc6;
        return simdjson::SUCCESS;
    }

    return simdjson::INCORRECT_TYPE;
}

void tag_invoke(serialize_tag, builder::string_builder& builder,const Flags<GamepadButtonType>& payload){
    builder.start_array();
    if(payload.Value()==0){
        builder.append("South");
    }
    if (payload & GamepadButtonType::Invalid){
        
        builder.append("Invalid");
    }
    if (payload & GamepadButtonType::East){
        builder.append_comma();
        builder.append("East");
    }
    if (payload & GamepadButtonType::West){
        builder.append_comma();
        builder.append("West");
    }
    if (payload & GamepadButtonType::North){
        builder.append_comma();
        builder.append("North");
    }
    if (payload & GamepadButtonType::Back){
        builder.append_comma();
        builder.append("Back");
    }
    if (payload & GamepadButtonType::Guide){
        builder.append_comma();
        builder.append("Guide");
    }
    if (payload & GamepadButtonType::Start){
        builder.append_comma();
        builder.append("Start");
    }
    if (payload & GamepadButtonType::LeftStick){
        builder.append_comma();
        builder.append("LeftStick");
    }
    if (payload & GamepadButtonType::RightStick){
        builder.append_comma();
        builder.append("RightStick");
    }
    if (payload & GamepadButtonType::LeftShoulder){
        builder.append_comma();
        builder.append("LeftShoulder");
    }
    if (payload & GamepadButtonType::RightShoulder){
        builder.append_comma();
        builder.append("RightShoulder");
    }
    if (payload & GamepadButtonType::DpadUp){
        builder.append_comma();
        builder.append("DpadUp");
    }
    if (payload & GamepadButtonType::DpadDown){
        builder.append_comma();
        builder.append("DpadDown");
    }
    if (payload & GamepadButtonType::DpadLeft){
        builder.append_comma();
        builder.append("DpadLeft");
    }
    if (payload & GamepadButtonType::DpadRight){
        builder.append_comma();
        builder.append("DpadRight");
    }
    if (payload & GamepadButtonType::Misc1){
        builder.append_comma();
        builder.append("Misc1");
    }
    if (payload & GamepadButtonType::RightPaddle1){
        builder.append_comma();
        builder.append("RightPaddle1");
    }
    if (payload & GamepadButtonType::LeftPaddle1){
        builder.append_comma();
        builder.append("LeftPaddle1");
    }
    if (payload & GamepadButtonType::RightPaddle2){
        builder.append_comma();
        builder.append("RightPaddle2");
    }
    if (payload & GamepadButtonType::LeftPaddle2){
        builder.append_comma();
        builder.append("LeftPaddle2");
    }
    if (payload & GamepadButtonType::Touchpad){
        builder.append_comma();
        builder.append("Touchpad");
    }
    if (payload & GamepadButtonType::Misc2){
        builder.append_comma();
        builder.append("Misc2");
    }
    if (payload & GamepadButtonType::Misc3){
        builder.append_comma();
        builder.append("Misc3");
    }
    if (payload & GamepadButtonType::Misc4){
        builder.append_comma();
        builder.append("Misc4");
    }
    if (payload & GamepadButtonType::Misc5){
        builder.append_comma();
        builder.append("Misc5");
    }
    if (payload & GamepadButtonType::Misc6){
        builder.append_comma();
        builder.append("Misc6");
    }
    builder.end_array();
}

auto tag_invoke(deserialize_tag, ondemand::document& val,Flags<GamepadButtonType>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "Invalid") {
            payload |= GamepadButtonType::Invalid;
            match = true;
        }
        if (value == "South") {
            payload |= GamepadButtonType::South;
            match = true;
        }
        if (value == "East") {
            payload |= GamepadButtonType::East;
            match = true;
        }
        if (value == "West") {
            payload |= GamepadButtonType::West;
            match = true;
        }
        if (value == "North") {
            payload |= GamepadButtonType::North;
            match = true;
        }
        if (value == "Back") {
            payload |= GamepadButtonType::Back;
            match = true;
        }
        if (value == "Guide") {
            payload |= GamepadButtonType::Guide;
            match = true;
        }
        if (value == "Start") {
            payload |= GamepadButtonType::Start;
            match = true;
        }
        if (value == "LeftStick") {
            payload |= GamepadButtonType::LeftStick;
            match = true;
        }
        if (value == "RightStick") {
            payload |= GamepadButtonType::RightStick;
            match = true;
        }
        if (value == "LeftShoulder") {
            payload |= GamepadButtonType::LeftShoulder;
            match = true;
        }
        if (value == "RightShoulder") {
            payload |= GamepadButtonType::RightShoulder;
            match = true;
        }
        if (value == "DpadUp") {
            payload |= GamepadButtonType::DpadUp;
            match = true;
        }
        if (value == "DpadDown") {
            payload |= GamepadButtonType::DpadDown;
            match = true;
        }
        if (value == "DpadLeft") {
            payload |= GamepadButtonType::DpadLeft;
            match = true;
        }
        if (value == "DpadRight") {
            payload |= GamepadButtonType::DpadRight;
            match = true;
        }
        if (value == "Misc1") {
            payload |= GamepadButtonType::Misc1;
            match = true;
        }
        if (value == "RightPaddle1") {
            payload |= GamepadButtonType::RightPaddle1;
            match = true;
        }
        if (value == "LeftPaddle1") {
            payload |= GamepadButtonType::LeftPaddle1;
            match = true;
        }
        if (value == "RightPaddle2") {
            payload |= GamepadButtonType::RightPaddle2;
            match = true;
        }
        if (value == "LeftPaddle2") {
            payload |= GamepadButtonType::LeftPaddle2;
            match = true;
        }
        if (value == "Touchpad") {
            payload |= GamepadButtonType::Touchpad;
            match = true;
        }
        if (value == "Misc2") {
            payload |= GamepadButtonType::Misc2;
            match = true;
        }
        if (value == "Misc3") {
            payload |= GamepadButtonType::Misc3;
            match = true;
        }
        if (value == "Misc4") {
            payload |= GamepadButtonType::Misc4;
            match = true;
        }
        if (value == "Misc5") {
            payload |= GamepadButtonType::Misc5;
            match = true;
        }
        if (value == "Misc6") {
            payload |= GamepadButtonType::Misc6;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag, ondemand::value& val,Flags<GamepadButtonType>& payload){
    simdjson::ondemand::array values;

    auto error = val.get_array().get(values);
    if (error) {
        return error;
    }
    payload  = {};

    for(auto item:values){
        std::string_view value;
        if(auto error = item.get_string().get(value)){
            return error;
        }
        bool match = false;
        if (value == "Invalid") {
            payload |= GamepadButtonType::Invalid;
            match = true;
        }
        if (value == "South") {
            payload |= GamepadButtonType::South;
            match = true;
        }
        if (value == "East") {
            payload |= GamepadButtonType::East;
            match = true;
        }
        if (value == "West") {
            payload |= GamepadButtonType::West;
            match = true;
        }
        if (value == "North") {
            payload |= GamepadButtonType::North;
            match = true;
        }
        if (value == "Back") {
            payload |= GamepadButtonType::Back;
            match = true;
        }
        if (value == "Guide") {
            payload |= GamepadButtonType::Guide;
            match = true;
        }
        if (value == "Start") {
            payload |= GamepadButtonType::Start;
            match = true;
        }
        if (value == "LeftStick") {
            payload |= GamepadButtonType::LeftStick;
            match = true;
        }
        if (value == "RightStick") {
            payload |= GamepadButtonType::RightStick;
            match = true;
        }
        if (value == "LeftShoulder") {
            payload |= GamepadButtonType::LeftShoulder;
            match = true;
        }
        if (value == "RightShoulder") {
            payload |= GamepadButtonType::RightShoulder;
            match = true;
        }
        if (value == "DpadUp") {
            payload |= GamepadButtonType::DpadUp;
            match = true;
        }
        if (value == "DpadDown") {
            payload |= GamepadButtonType::DpadDown;
            match = true;
        }
        if (value == "DpadLeft") {
            payload |= GamepadButtonType::DpadLeft;
            match = true;
        }
        if (value == "DpadRight") {
            payload |= GamepadButtonType::DpadRight;
            match = true;
        }
        if (value == "Misc1") {
            payload |= GamepadButtonType::Misc1;
            match = true;
        }
        if (value == "RightPaddle1") {
            payload |= GamepadButtonType::RightPaddle1;
            match = true;
        }
        if (value == "LeftPaddle1") {
            payload |= GamepadButtonType::LeftPaddle1;
            match = true;
        }
        if (value == "RightPaddle2") {
            payload |= GamepadButtonType::RightPaddle2;
            match = true;
        }
        if (value == "LeftPaddle2") {
            payload |= GamepadButtonType::LeftPaddle2;
            match = true;
        }
        if (value == "Touchpad") {
            payload |= GamepadButtonType::Touchpad;
            match = true;
        }
        if (value == "Misc2") {
            payload |= GamepadButtonType::Misc2;
            match = true;
        }
        if (value == "Misc3") {
            payload |= GamepadButtonType::Misc3;
            match = true;
        }
        if (value == "Misc4") {
            payload |= GamepadButtonType::Misc4;
            match = true;
        }
        if (value == "Misc5") {
            payload |= GamepadButtonType::Misc5;
            match = true;
        }
        if (value == "Misc6") {
            payload |= GamepadButtonType::Misc6;
            match = true;
        }
        if (!match) {
            return simdjson::INCORRECT_TYPE;
        }
    }
    return simdjson::SUCCESS;
}

}
