/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module relationship.serialize;
export import relationship;




import simdjson;
import std;

export namespace simdjson{

void tag_invoke(serialize_tag, builder::string_builder& builder,const Relationship& payload){
    builder.start_object();
    builder.template append_key_value<"m_children">(payload.m_children);
    builder.end_object();
}

auto tag_invoke(deserialize_tag,ondemand::document& val,Relationship& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_children"].get(payload.m_children))){
        return error;
    }
    return simdjson::SUCCESS;
}

auto tag_invoke(deserialize_tag,ondemand::value& val,Relationship& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_children"].get(payload.m_children))){
        return error;
    }
    return simdjson::SUCCESS;
}

}
