/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module transform:serialize;

import :type;
import simdjson;
import std;


export namespace simdjson{

template <typename builder_type>
void tag_invoke(serialize_tag, builder_type& builder,const Transform& payload){
    builder.start_object();
    builder.template append_key_value<"m_pose">(payload.m_pose);
    builder.append_comma();
    builder.template append_key_value<"m_global_pose">(payload.m_global_pose);
    builder.end_object();
}

template<typename simdjson_value>
auto tag_invoke(deserialize_tag,simdjson_value& val,Transform& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_pose"].get(payload.m_pose))){
        return error;
    }
    if((error=obj["m_global_pose"].get(payload.m_global_pose))){
        return error;
    }
    return simdjson::SUCCESS;
}

}
