/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
export module prefab:serialize;

import :type;
import simdjson;
import std;


export namespace simdjson{

template <typename builder_type>
void tag_invoke(serialize_tag, builder_type& builder,const Prefab& payload){
    builder.start_object();
    builder.template append_key_value<"m_sprite">(payload.m_sprite);
    builder.append_comma();
    builder.template append_key_value<"m_transform">(payload.m_transform);
    builder.append_comma();
    builder.template append_key_value<"m_relation">(payload.m_relation);
    builder.end_object();
}

template<typename simdjson_value>
auto tag_invoke(deserialize_tag,simdjson_value& val,Prefab& payload){
    ondemand::object obj;
    auto error = val.get_object().get(obj);
    if(error){
        return error;
    }
    if((error=obj["m_sprite"].get(payload.m_sprite))){
        return error;
    }
    if((error=obj["m_transform"].get(payload.m_transform))){
        return error;
    }
    if((error=obj["m_relation"].get(payload.m_relation))){
        return error;
    }
    return simdjson::SUCCESS;
}

}
