/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module flip.display;

import flip;
import flag;
import instance_display;
import imgui_id_generator;


import std;

export{

void InstanceDisplay(const char* name, Flip& value){
    static  const std::unordered_map<Flip, int> enum_to_idx = {
        { Flip::None, 0 },
        { Flip::Horizontal, 1 },
        { Flip::Vertical, 2 },
    };

    static  const std::unordered_map<int, Flip> idx_to_enum = {
        { 0, Flip::None },
        { 1, Flip::Horizontal },
        { 2, Flip::Vertical },
    };

    const char* const items[] = {
        "None",
        "Horizontal",
        "Vertical",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);

    value = idx_to_enum.at(cur_item);

    ImGui::PopID();
}

void InstanceDisplay(const char* name, const Flip& value){
    ImGui::BeginDisabled(true);
    static const std::unordered_map<Flip, int> enum_to_idx = {
        { Flip::None, 0 },
        { Flip::Horizontal, 1 },
        { Flip::Vertical, 2 },
    };

    const char* const items[] = {
        "None",
        "Horizontal",
        "Vertical",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);
    ImGui::EndDisabled();

    ImGui::PopID();
}

void InstanceDisplay(const char* name, Flags<Flip>& value){
    static const Flip items[] = {
        Flip::None,
        Flip::Horizontal,
        Flip::Vertical,
    };

    static const char* item_names[] = {
        "None",
        "Horizontal",
        "Vertical",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(Flip); i++) {
        auto item = items[i];
        auto name = item_names[i];

        ImGui::PushID(ImGuiIDGenerator::Gen());
        if (value.Value() == 0) {
            if (static_cast<int>(item) == 0) {
                ImGui::BeginDisabled(false);
            } else {
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::BeginDisabled(true);
            }
        } else {
            if (static_cast<int>(item) == 0){
                ImGui::BeginDisabled(true);
            } else if (value & item) {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("del")) {
                    value.Remove(item);
                }
            } else {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::EndDisabled();
                ImGui::BeginDisabled(true);
            }
        }
        ImGui::PopID();
        ImGui::SameLine();
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

void InstanceDisplay(const char* name, const Flags<Flip>& value){
    static const Flip items[] = {
            Flip::None,
            Flip::Horizontal,
            Flip::Vertical,
    };

    static const char* item_names[] = {
        "None",
        "Horizontal",
        "Vertical",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(Flip); i++) {
        auto item = items[i];
        auto name = item_names[i];
        ImGui::BeginDisabled(true);
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

}
