/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module inputconfig.display;

import inputconfig;

import instance_display;
import imgui_id_generator;
import key.display;
import padkey.display;
import mousekey.display;

import std;

export{

void InstanceDisplay(const char* name, KeyboardInput& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_key", value.m_key);
    InstanceDisplay("m_scale", value.m_scale);
}

void InstanceDisplay(const char* name, const KeyboardInput& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_key", value.m_key);
    InstanceDisplay("m_scale", value.m_scale);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, GamepadButtonInput& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_button", value.m_button);
    InstanceDisplay("m_scale", value.m_scale);
}

void InstanceDisplay(const char* name, const GamepadButtonInput& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_button", value.m_button);
    InstanceDisplay("m_scale", value.m_scale);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, GamepadAxisInput& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_axis", value.m_axis);
    InstanceDisplay("m_scale", value.m_scale);
}

void InstanceDisplay(const char* name, const GamepadAxisInput& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_axis", value.m_axis);
    InstanceDisplay("m_scale", value.m_scale);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, MouseButtonInput& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_type", value.m_type);
    InstanceDisplay("m_scale", value.m_scale);
}

void InstanceDisplay(const char* name, const MouseButtonInput& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_type", value.m_type);
    InstanceDisplay("m_scale", value.m_scale);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, InputActionConfig& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_name", value.m_name);
    InstanceDisplay("m_keyboard", value.m_keyboard);
    InstanceDisplay("m_gamepad", value.m_gamepad);
}

void InstanceDisplay(const char* name, const InputActionConfig& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_name", value.m_name);
    InstanceDisplay("m_keyboard", value.m_keyboard);
    InstanceDisplay("m_gamepad", value.m_gamepad);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, InputAxisConfig& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_name", value.m_name);
    InstanceDisplay("m_keyboard", value.m_keyboard);
    InstanceDisplay("m_gamepad_axis", value.m_gamepad_axis);
    InstanceDisplay("m_gamepad_button", value.m_gamepad_button);
    InstanceDisplay("m_mouse_vertical", value.m_mouse_vertical);
    InstanceDisplay("m_mouse_horizontal", value.m_mouse_horizontal);
}

void InstanceDisplay(const char* name, const InputAxisConfig& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_name", value.m_name);
    InstanceDisplay("m_keyboard", value.m_keyboard);
    InstanceDisplay("m_gamepad_axis", value.m_gamepad_axis);
    InstanceDisplay("m_gamepad_button", value.m_gamepad_button);
    InstanceDisplay("m_mouse_vertical", value.m_mouse_vertical);
    InstanceDisplay("m_mouse_horizontal", value.m_mouse_horizontal);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, InputConfig& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_action", value.m_action);
    InstanceDisplay("m_axis", value.m_axis);
}

void InstanceDisplay(const char* name, const InputConfig& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_action", value.m_action);
    InstanceDisplay("m_axis", value.m_axis);
    ImGui::EndDisabled();
}

}
