/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module math.display;

import math;

import instance_display;
import imgui_id_generator;


import std;

export{


}
