/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module mousekey.display;

import mousekey;
import flag;
import instance_display;
import imgui_id_generator;


import std;

export{

void InstanceDisplay(const char* name, MouseButtonType& value){
    static  const std::unordered_map<MouseButtonType, int> enum_to_idx = {
        { MouseButtonType::Left, 1 },
        { MouseButtonType::Right, 2 },
        { MouseButtonType::Middle, 3 },
        { MouseButtonType::X1, 4 },
        { MouseButtonType::X2, 5 },
    };

    static  const std::unordered_map<int, MouseButtonType> idx_to_enum = {
        { 1, MouseButtonType::Left },
        { 2, MouseButtonType::Right },
        { 3, MouseButtonType::Middle },
        { 4, MouseButtonType::X1 },
        { 5, MouseButtonType::X2 },
    };

    const char* const items[] = {
        "Left",
        "Right",
        "Middle",
        "X1",
        "X2",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);

    value = idx_to_enum.at(cur_item);

    ImGui::PopID();
}

void InstanceDisplay(const char* name, const MouseButtonType& value){
    ImGui::BeginDisabled(true);
    static const std::unordered_map<MouseButtonType, int> enum_to_idx = {
        { MouseButtonType::Left, 1 },
        { MouseButtonType::Right, 2 },
        { MouseButtonType::Middle, 3 },
        { MouseButtonType::X1, 4 },
        { MouseButtonType::X2, 5 },
    };

    const char* const items[] = {
        "Left",
        "Right",
        "Middle",
        "X1",
        "X2",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);
    ImGui::EndDisabled();

    ImGui::PopID();
}

void InstanceDisplay(const char* name, Flags<MouseButtonType>& value){
    static const MouseButtonType items[] = {
        MouseButtonType::Left,
        MouseButtonType::Right,
        MouseButtonType::Middle,
        MouseButtonType::X1,
        MouseButtonType::X2,
    };

    static const char* item_names[] = {
        "Left",
        "Right",
        "Middle",
        "X1",
        "X2",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(MouseButtonType); i++) {
        auto item = items[i];
        auto name = item_names[i];

        ImGui::PushID(ImGuiIDGenerator::Gen());
        if (value.Value() == 0) {
            if (static_cast<int>(item) == 0) {
                ImGui::BeginDisabled(false);
            } else {
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::BeginDisabled(true);
            }
        } else {
            if (static_cast<int>(item) == 0){
                ImGui::BeginDisabled(true);
            } else if (value & item) {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("del")) {
                    value.Remove(item);
                }
            } else {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::EndDisabled();
                ImGui::BeginDisabled(true);
            }
        }
        ImGui::PopID();
        ImGui::SameLine();
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

void InstanceDisplay(const char* name, const Flags<MouseButtonType>& value){
    static const MouseButtonType items[] = {
            MouseButtonType::Left,
            MouseButtonType::Right,
            MouseButtonType::Middle,
            MouseButtonType::X1,
            MouseButtonType::X2,
    };

    static const char* item_names[] = {
        "Left",
        "Right",
        "Middle",
        "X1",
        "X2",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(MouseButtonType); i++) {
        auto item = items[i];
        auto name = item_names[i];
        ImGui::BeginDisabled(true);
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

}
