/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module padkey.display;

import padkey;
import flag;
import instance_display;
import imgui_id_generator;


import std;

export{

void InstanceDisplay(const char* name, GamepadAxisType& value){
    static  const std::unordered_map<GamepadAxisType, int> enum_to_idx = {
        { GamepadAxisType::Invalid, -1 },
        { GamepadAxisType::LeftX, 0 },
        { GamepadAxisType::LeftY, 1 },
        { GamepadAxisType::RightX, 2 },
        { GamepadAxisType::RightY, 3 },
        { GamepadAxisType::LeftTrigger, 4 },
        { GamepadAxisType::RightTrigger, 5 },
    };

    static  const std::unordered_map<int, GamepadAxisType> idx_to_enum = {
        { -1, GamepadAxisType::Invalid },
        { 0, GamepadAxisType::LeftX },
        { 1, GamepadAxisType::LeftY },
        { 2, GamepadAxisType::RightX },
        { 3, GamepadAxisType::RightY },
        { 4, GamepadAxisType::LeftTrigger },
        { 5, GamepadAxisType::RightTrigger },
    };

    const char* const items[] = {
        "Invalid",
        "LeftX",
        "LeftY",
        "RightX",
        "RightY",
        "LeftTrigger",
        "RightTrigger",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);

    value = idx_to_enum.at(cur_item);

    ImGui::PopID();
}

void InstanceDisplay(const char* name, const GamepadAxisType& value){
    ImGui::BeginDisabled(true);
    static const std::unordered_map<GamepadAxisType, int> enum_to_idx = {
        { GamepadAxisType::Invalid, -1 },
        { GamepadAxisType::LeftX, 0 },
        { GamepadAxisType::LeftY, 1 },
        { GamepadAxisType::RightX, 2 },
        { GamepadAxisType::RightY, 3 },
        { GamepadAxisType::LeftTrigger, 4 },
        { GamepadAxisType::RightTrigger, 5 },
    };

    const char* const items[] = {
        "Invalid",
        "LeftX",
        "LeftY",
        "RightX",
        "RightY",
        "LeftTrigger",
        "RightTrigger",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);
    ImGui::EndDisabled();

    ImGui::PopID();
}

void InstanceDisplay(const char* name, Flags<GamepadAxisType>& value){
    static const GamepadAxisType items[] = {
        GamepadAxisType::Invalid,
        GamepadAxisType::LeftX,
        GamepadAxisType::LeftY,
        GamepadAxisType::RightX,
        GamepadAxisType::RightY,
        GamepadAxisType::LeftTrigger,
        GamepadAxisType::RightTrigger,
    };

    static const char* item_names[] = {
        "Invalid",
        "LeftX",
        "LeftY",
        "RightX",
        "RightY",
        "LeftTrigger",
        "RightTrigger",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(GamepadAxisType); i++) {
        auto item = items[i];
        auto name = item_names[i];

        ImGui::PushID(ImGuiIDGenerator::Gen());
        if (value.Value() == 0) {
            if (static_cast<int>(item) == 0) {
                ImGui::BeginDisabled(false);
            } else {
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::BeginDisabled(true);
            }
        } else {
            if (static_cast<int>(item) == 0){
                ImGui::BeginDisabled(true);
            } else if (value & item) {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("del")) {
                    value.Remove(item);
                }
            } else {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::EndDisabled();
                ImGui::BeginDisabled(true);
            }
        }
        ImGui::PopID();
        ImGui::SameLine();
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

void InstanceDisplay(const char* name, const Flags<GamepadAxisType>& value){
    static const GamepadAxisType items[] = {
            GamepadAxisType::Invalid,
            GamepadAxisType::LeftX,
            GamepadAxisType::LeftY,
            GamepadAxisType::RightX,
            GamepadAxisType::RightY,
            GamepadAxisType::LeftTrigger,
            GamepadAxisType::RightTrigger,
    };

    static const char* item_names[] = {
        "Invalid",
        "LeftX",
        "LeftY",
        "RightX",
        "RightY",
        "LeftTrigger",
        "RightTrigger",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(GamepadAxisType); i++) {
        auto item = items[i];
        auto name = item_names[i];
        ImGui::BeginDisabled(true);
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

void InstanceDisplay(const char* name, GamepadButtonType& value){
    static  const std::unordered_map<GamepadButtonType, int> enum_to_idx = {
        { GamepadButtonType::Invalid, -1 },
        { GamepadButtonType::South, 0 },
        { GamepadButtonType::East, 1 },
        { GamepadButtonType::West, 2 },
        { GamepadButtonType::North, 3 },
        { GamepadButtonType::Back, 4 },
        { GamepadButtonType::Guide, 5 },
        { GamepadButtonType::Start, 6 },
        { GamepadButtonType::LeftStick, 7 },
        { GamepadButtonType::RightStick, 8 },
        { GamepadButtonType::LeftShoulder, 9 },
        { GamepadButtonType::RightShoulder, 10 },
        { GamepadButtonType::DpadUp, 11 },
        { GamepadButtonType::DpadDown, 12 },
        { GamepadButtonType::DpadLeft, 13 },
        { GamepadButtonType::DpadRight, 14 },
        { GamepadButtonType::Misc1, 15 },
        { GamepadButtonType::RightPaddle1, 16 },
        { GamepadButtonType::LeftPaddle1, 17 },
        { GamepadButtonType::RightPaddle2, 18 },
        { GamepadButtonType::LeftPaddle2, 19 },
        { GamepadButtonType::Touchpad, 20 },
        { GamepadButtonType::Misc2, 21 },
        { GamepadButtonType::Misc3, 22 },
        { GamepadButtonType::Misc4, 23 },
        { GamepadButtonType::Misc5, 24 },
        { GamepadButtonType::Misc6, 25 },
    };

    static  const std::unordered_map<int, GamepadButtonType> idx_to_enum = {
        { -1, GamepadButtonType::Invalid },
        { 0, GamepadButtonType::South },
        { 1, GamepadButtonType::East },
        { 2, GamepadButtonType::West },
        { 3, GamepadButtonType::North },
        { 4, GamepadButtonType::Back },
        { 5, GamepadButtonType::Guide },
        { 6, GamepadButtonType::Start },
        { 7, GamepadButtonType::LeftStick },
        { 8, GamepadButtonType::RightStick },
        { 9, GamepadButtonType::LeftShoulder },
        { 10, GamepadButtonType::RightShoulder },
        { 11, GamepadButtonType::DpadUp },
        { 12, GamepadButtonType::DpadDown },
        { 13, GamepadButtonType::DpadLeft },
        { 14, GamepadButtonType::DpadRight },
        { 15, GamepadButtonType::Misc1 },
        { 16, GamepadButtonType::RightPaddle1 },
        { 17, GamepadButtonType::LeftPaddle1 },
        { 18, GamepadButtonType::RightPaddle2 },
        { 19, GamepadButtonType::LeftPaddle2 },
        { 20, GamepadButtonType::Touchpad },
        { 21, GamepadButtonType::Misc2 },
        { 22, GamepadButtonType::Misc3 },
        { 23, GamepadButtonType::Misc4 },
        { 24, GamepadButtonType::Misc5 },
        { 25, GamepadButtonType::Misc6 },
    };

    const char* const items[] = {
        "Invalid",
        "South",
        "East",
        "West",
        "North",
        "Back",
        "Guide",
        "Start",
        "LeftStick",
        "RightStick",
        "LeftShoulder",
        "RightShoulder",
        "DpadUp",
        "DpadDown",
        "DpadLeft",
        "DpadRight",
        "Misc1",
        "RightPaddle1",
        "LeftPaddle1",
        "RightPaddle2",
        "LeftPaddle2",
        "Touchpad",
        "Misc2",
        "Misc3",
        "Misc4",
        "Misc5",
        "Misc6",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);

    value = idx_to_enum.at(cur_item);

    ImGui::PopID();
}

void InstanceDisplay(const char* name, const GamepadButtonType& value){
    ImGui::BeginDisabled(true);
    static const std::unordered_map<GamepadButtonType, int> enum_to_idx = {
        { GamepadButtonType::Invalid, -1 },
        { GamepadButtonType::South, 0 },
        { GamepadButtonType::East, 1 },
        { GamepadButtonType::West, 2 },
        { GamepadButtonType::North, 3 },
        { GamepadButtonType::Back, 4 },
        { GamepadButtonType::Guide, 5 },
        { GamepadButtonType::Start, 6 },
        { GamepadButtonType::LeftStick, 7 },
        { GamepadButtonType::RightStick, 8 },
        { GamepadButtonType::LeftShoulder, 9 },
        { GamepadButtonType::RightShoulder, 10 },
        { GamepadButtonType::DpadUp, 11 },
        { GamepadButtonType::DpadDown, 12 },
        { GamepadButtonType::DpadLeft, 13 },
        { GamepadButtonType::DpadRight, 14 },
        { GamepadButtonType::Misc1, 15 },
        { GamepadButtonType::RightPaddle1, 16 },
        { GamepadButtonType::LeftPaddle1, 17 },
        { GamepadButtonType::RightPaddle2, 18 },
        { GamepadButtonType::LeftPaddle2, 19 },
        { GamepadButtonType::Touchpad, 20 },
        { GamepadButtonType::Misc2, 21 },
        { GamepadButtonType::Misc3, 22 },
        { GamepadButtonType::Misc4, 23 },
        { GamepadButtonType::Misc5, 24 },
        { GamepadButtonType::Misc6, 25 },
    };

    const char* const items[] = {
        "Invalid",
        "South",
        "East",
        "West",
        "North",
        "Back",
        "Guide",
        "Start",
        "LeftStick",
        "RightStick",
        "LeftShoulder",
        "RightShoulder",
        "DpadUp",
        "DpadDown",
        "DpadLeft",
        "DpadRight",
        "Misc1",
        "RightPaddle1",
        "LeftPaddle1",
        "RightPaddle2",
        "LeftPaddle2",
        "Touchpad",
        "Misc2",
        "Misc3",
        "Misc4",
        "Misc5",
        "Misc6",
    };

    ImGui::PushID(ImGuiIDGenerator::Gen());

    int cur_item = enum_to_idx.at(value);
    ImGui::Combo(name, &cur_item, items, 3);
    ImGui::EndDisabled();

    ImGui::PopID();
}

void InstanceDisplay(const char* name, Flags<GamepadButtonType>& value){
    static const GamepadButtonType items[] = {
        GamepadButtonType::Invalid,
        GamepadButtonType::South,
        GamepadButtonType::East,
        GamepadButtonType::West,
        GamepadButtonType::North,
        GamepadButtonType::Back,
        GamepadButtonType::Guide,
        GamepadButtonType::Start,
        GamepadButtonType::LeftStick,
        GamepadButtonType::RightStick,
        GamepadButtonType::LeftShoulder,
        GamepadButtonType::RightShoulder,
        GamepadButtonType::DpadUp,
        GamepadButtonType::DpadDown,
        GamepadButtonType::DpadLeft,
        GamepadButtonType::DpadRight,
        GamepadButtonType::Misc1,
        GamepadButtonType::RightPaddle1,
        GamepadButtonType::LeftPaddle1,
        GamepadButtonType::RightPaddle2,
        GamepadButtonType::LeftPaddle2,
        GamepadButtonType::Touchpad,
        GamepadButtonType::Misc2,
        GamepadButtonType::Misc3,
        GamepadButtonType::Misc4,
        GamepadButtonType::Misc5,
        GamepadButtonType::Misc6,
    };

    static const char* item_names[] = {
        "Invalid",
        "South",
        "East",
        "West",
        "North",
        "Back",
        "Guide",
        "Start",
        "LeftStick",
        "RightStick",
        "LeftShoulder",
        "RightShoulder",
        "DpadUp",
        "DpadDown",
        "DpadLeft",
        "DpadRight",
        "Misc1",
        "RightPaddle1",
        "LeftPaddle1",
        "RightPaddle2",
        "LeftPaddle2",
        "Touchpad",
        "Misc2",
        "Misc3",
        "Misc4",
        "Misc5",
        "Misc6",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(GamepadButtonType); i++) {
        auto item = items[i];
        auto name = item_names[i];

        ImGui::PushID(ImGuiIDGenerator::Gen());
        if (value.Value() == 0) {
            if (static_cast<int>(item) == 0) {
                ImGui::BeginDisabled(false);
            } else {
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::BeginDisabled(true);
            }
        } else {
            if (static_cast<int>(item) == 0){
                ImGui::BeginDisabled(true);
            } else if (value & item) {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("del")) {
                    value.Remove(item);
                }
            } else {
                ImGui::BeginDisabled(false);
                if (ImGui::Button("add")) {
                    value |= item;
                }
                ImGui::EndDisabled();
                ImGui::BeginDisabled(true);
            }
        }
        ImGui::PopID();
        ImGui::SameLine();
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

void InstanceDisplay(const char* name, const Flags<GamepadButtonType>& value){
    static const GamepadButtonType items[] = {
            GamepadButtonType::Invalid,
            GamepadButtonType::South,
            GamepadButtonType::East,
            GamepadButtonType::West,
            GamepadButtonType::North,
            GamepadButtonType::Back,
            GamepadButtonType::Guide,
            GamepadButtonType::Start,
            GamepadButtonType::LeftStick,
            GamepadButtonType::RightStick,
            GamepadButtonType::LeftShoulder,
            GamepadButtonType::RightShoulder,
            GamepadButtonType::DpadUp,
            GamepadButtonType::DpadDown,
            GamepadButtonType::DpadLeft,
            GamepadButtonType::DpadRight,
            GamepadButtonType::Misc1,
            GamepadButtonType::RightPaddle1,
            GamepadButtonType::LeftPaddle1,
            GamepadButtonType::RightPaddle2,
            GamepadButtonType::LeftPaddle2,
            GamepadButtonType::Touchpad,
            GamepadButtonType::Misc2,
            GamepadButtonType::Misc3,
            GamepadButtonType::Misc4,
            GamepadButtonType::Misc5,
            GamepadButtonType::Misc6,
    };

    static const char* item_names[] = {
        "Invalid",
        "South",
        "East",
        "West",
        "North",
        "Back",
        "Guide",
        "Start",
        "LeftStick",
        "RightStick",
        "LeftShoulder",
        "RightShoulder",
        "DpadUp",
        "DpadDown",
        "DpadLeft",
        "DpadRight",
        "Misc1",
        "RightPaddle1",
        "LeftPaddle1",
        "RightPaddle2",
        "LeftPaddle2",
        "Touchpad",
        "Misc2",
        "Misc3",
        "Misc4",
        "Misc5",
        "Misc6",
    };

    ImGui::Text("%s", name);

    for (size_t i = 0; i < sizeof(items) / sizeof(GamepadButtonType); i++) {
        auto item = items[i];
        auto name = item_names[i];
        ImGui::BeginDisabled(true);
        ImGui::Text("%s", name);
        ImGui::EndDisabled();
    }
}

}
