/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module prefab.display;

import prefab;

import instance_display;
import imgui_id_generator;
import sprite.display;
import math.display;
import relationship.display;

import std;

export{

void InstanceDisplay(const char* name, Prefab& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_sprite", value.m_sprite);
    InstanceDisplay("m_transform", value.m_transform);
    InstanceDisplay("m_relation", value.m_relation);
}

void InstanceDisplay(const char* name, const Prefab& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_sprite", value.m_sprite);
    InstanceDisplay("m_transform", value.m_transform);
    InstanceDisplay("m_relation", value.m_relation);
    ImGui::EndDisabled();
}

void InstanceDisplay(const char* name, EntityInstance& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_entity", value.m_entity);
    InstanceDisplay("m_data", value.m_data);
}

void InstanceDisplay(const char* name, const EntityInstance& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_entity", value.m_entity);
    InstanceDisplay("m_data", value.m_data);
    ImGui::EndDisabled();
}

}
