/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module relationship.display;

import relationship;

import instance_display;
import imgui_id_generator;


import std;

export{

void InstanceDisplay(const char* name, Relationship& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_children", value.m_children);
}

void InstanceDisplay(const char* name, const Relationship& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_children", value.m_children);
    ImGui::EndDisabled();
}

}
