/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module sprite.display;

import sprite;

import instance_display;
import imgui_id_generator;
import math.display;
import flip.display;

import std;

export{

void InstanceDisplay(const char* name, Sprite& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_image", value.m_image);
    InstanceDisplay("m_region", value.m_region);
    InstanceDisplay("m_size", value.m_size);
    InstanceDisplay("m_flip", value.m_flip);
}

void InstanceDisplay(const char* name, const Sprite& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_image", value.m_image);
    InstanceDisplay("m_region", value.m_region);
    InstanceDisplay("m_size", value.m_size);
    InstanceDisplay("m_flip", value.m_flip);
    ImGui::EndDisabled();
}

}
