/////////////////////////////////////////////////////////////////////
/// WARN: THIS FILE GENERATED BY schema_parser, DONT CHANGE IT!!! ///
/////////////////////////////////////////////////////////////////////

module;
#include <imgui.h>
export module transform.display;

import transform;

import instance_display;
import imgui_id_generator;
import math.display;

import std;

export{

void InstanceDisplay(const char* name, Transform& value){ 
    ImGui::Text("%s", name);
    InstanceDisplay("m_pose", value.m_pose);
    InstanceDisplay("m_global_pose", value.m_global_pose);
}

void InstanceDisplay(const char* name, const Transform& value){
    ImGui::BeginDisabled(true);
    ImGui::Text("%s", name);
    InstanceDisplay("m_pose", value.m_pose);
    InstanceDisplay("m_global_pose", value.m_global_pose);
    ImGui::EndDisabled();
}

}
